#!/usr/bin/env sh
COMMIT_MSG_FILE=$1

# 현재 브랜치에서 이슈 번호 추출
branch_name=`git rev-parse --abbrev-ref HEAD`
issue_number=`echo ${branch_name} | cut -d '/' -f2`

# 커밋 메시지에서 이슈 번호 추출
commit_message=`cat ${COMMIT_MSG_FILE}`
if [[ $commit_message =~ ^\[#([0-9]+)\].* ]]; then
    existing_issue_number=${BASH_REMATCH[1]}
else
    existing_issue_number=""
fi

# 이슈 번호가 커밋 메시지에 없는 경우 추가
if [[ -z "$existing_issue_number" ]]; then
    sed -i.bak "1s/^/[#$issue_number] /" ${COMMIT_MSG_FILE}
fi
